function mv_declareClassSelectDependent(){dojo.declare("MV.SelectDependent",null,{FieldArray:null,ValueArray:null,Identify:!0,AutoComplete:!0,ZoomTo:!0,ShowRec:!0,FirstFName:"Categories",FPAlign:"left",Index:0,InitDropDownMenu:!1,constructor:function(b){dojo.mixin(this,b)},init:function(){this.InitDropDownMenu||(this.InitDropDownMenu=!0,dojo.byId("MVCategoriesMenu")&&this.createDropDownMenu())},fillSelect:function(b){if(null!=b.item){var a=b.id.substring(b.id.lastIndexOf("t")+1),d=parseInt(a.substring(a.lastIndexOf("_")+
1)),a=a.replace("_"+d,"_");if(b.item.value&&-1!=b.item.value[0].search(/MVClearSelection.+/))mv_clearFeatures(),this.clearSelect(a,1);else{b=mv_Map.Layers.item(this.id);for(var c=0;c<=d;c++){var e=dijit.byId("MVselectDependent"+a+c);if(0==c){var f=e.item.name[0];e.item.value&&""!=e.item.value[0]&&(f=e.item.value[0]);var g=this.FieldArray[c]+mv_makeSQLString2(b,f,this.ValueArray[c])}else g+=" and "+this.FieldArray[c]+mv_makeSQLString2(b,e.item.name,this.ValueArray[c])}f=g;b.XMLAccess&&(f=mv_selRecords(g,
this.id));if(d<this.FieldArray.length-1){g=[];e=this.FieldArray[d+1];for(c=0;c<f.length;c++)try{f[c].selectSingleNode(e),g.push(f[c].selectSingleNode(e).firstChild.nodeValue)}catch(h){}e=g.unique();0==this.ValueArray[d+1]?e.sort(mv_numsort2):e.sort();g=[];for(c=0;c<e.length;c++){var k={};k.name=e[c];g.push(k)}c=new dojo.store.Memory({data:g,idProperty:"name"});e=dijit.byId("MVselectDependent"+a+(d+1));e.reset();e.set("store",c);e.set("disabled",!1);this.clearSelect(a,d+2);1==g.length&&this.AutoComplete&&
e.set("item",c.data[0]);0==g.length&&(mv_selRecords2(b.XMLAccess,f,this.id,this.id,this.ZoomTo,!1,this.ShowRec,20),this.Identify&&(a=f[0].parentNode.getAttributeNode("id").value,mv_identify(a,"list")))}else mv_selRecords2(b.XMLAccess,f,this.id,this.id,this.ZoomTo,!1,this.ShowRec,20),this.Identify&&(a=f[0].parentNode.getAttributeNode("id").value,mv_identify(a,"list"))}}},clearSelect:function(b,a){for(;a<this.FieldArray.length;)selObj=dijit.byId("MVselectDependent"+b+a),selObj.set("disabled",!0),selObj.reset(),
a++},createDropDownMenu:function(){var b=mv_loadAttrTableFile(this.id,!0);if(null!=b){var a=mv_loadXMLDoc(mv_Doc.BaseURL+"embfiles/"+this.id+"_json.js","json");if(null!=a){for(var a=a.items,d=[],c=1;c<a.length;++c)d.push(a[c].name);a=mv_makeNode(document,"div",{id:"MVCategoriesMenu"+this.Index});dojo.byId("MVCategoriesMenu").appendChild(a);a=new dijit.DropDownMenu({style:"display:inline-table;vertical-align:middle;margin-left:10px","class":"MVCategoriesMenu"},a);b=this.doSelectDropDownMenu(d,this.FieldArray[0],
b,0);a.addChild(new dijit.PopupMenuItem({label:this.FirstFName,popup:b}));b.startup();a.startup()}}},doSelectDropDownMenu:function(b,a,d,c){for(var e=new dijit.DropDownMenu({style:"box-shadow:5px 5px 8px 5px #666"}),f=0;f<b.length;++f){var g=a+mv_makeSQLString2(mv_Map.Layers.item(this.id),b[f],this.ValueArray[c]),h='mv_showSubCategories("'+g+'",'+c+",this,"+this.Index+")";if(c<this.FieldArray.length-1){var k=d.query(g),k=d.getUniques(k,this.FieldArray[c+1],this.ValueArray[c+1]),g=g+(" and "+this.FieldArray[c+
1]),g=this.doSelectDropDownMenu(k,g,d,c+1);mv_writePopupMenuItem(e,b[f],g,h)}else h='mv_selRecordsStart("'+g+"\",'"+this.id+"',"+this.ZoomTo+",false,"+this.ShowRec+")",mv_writeLegendMenuItem(e,b[f],"",h)}e.startup();return e},showSubCategoriesInFP:function(b,a,d){var c=mv_loadAttrTableFile(this.id,!0);b=c.query(b);var e=new dijit.DropDownMenu({});sortIndex=this.FieldArray.length-1;c=c.recsSortByField(b,this.FieldArray[sortIndex],this.ValueArray[sortIndex],!1);for(b=0;b<c.length;++b){var f="";if(a<
sortIndex-1)try{f=c[b].obj.selectSingleNode(this.FieldArray[sortIndex-1]).firstChild.nodeValue,f=" ("+f+")"}catch(g){}var f=c[b].name+f,h="mv_zoomToExtent2('"+c[b].obj.parentNode.selectSingleNode("ext").firstChild.nodeValue+"',20)";mv_writeLegendMenuItem(e,f,"",h)}e.startup();dijit.byId("MVCategoriesMenu"+this.Index).onClose();a=dijit.byId("MVFPCategoriesContainer");null!=a?(a.set("content",e),a.set("title",d),a.startup(),a.bringToTop(),a.show(),a.set("style","width:auto;height:auto")):require(["dojox/layout/FloatingPane"],
function(a){a=new a({resizable:!1,dockable:!1,content:e,title:d,style:"position:absolute;top:120px;left:25px;width:auto;height:auto;visibility:hidden;z-index:5;"},"MVFPCategoriesContainer");a.startup();a.bringToTop();a.show();a.set("style","width:auto;height:auto");"right"==this.FPAlign&&a.set("style","left:"+(mv_Map.CurrentExt.Width-a.canvas.clientWidth-20)+"px")})}})}function mv_selectDependent(b,a){mv_Doc.SelectDependents[a].fillSelect(b)}
function mv_showSubCategories(b,a,d,c){mv_Doc.SelectDependents[c].showSubCategoriesInFP(b,a,d.label)}Array.prototype.unique=function(){var b={},a,d=this.length,c=[];for(a=0;a<d;a+=1)b[this[a]]=this[a];for(a in b)c.push(b[a]);return c};function mv_writePopupMenuItem(b,a,d,c){b.addChild(new dijit.PopupMenuItem({label:a,popup:d,onMouseUp:function(){eval(c)}}))}
function mv_zoomObjectDojo(b,a,d,c,e,f,g){if(b)if(b.value&&-1!=b.value[0].search(/MVClearSelection.+/))mv_clearFeatures();else{var h=Array.isArray(b.name)?b.name[0]:b.name;b.value&&""!=b.value[0]&&(h=b.value[0]);b=mv_Map.Layers.item(d);a+=mv_makeSQLString2(b,h,c);mv_selRecordsStart(a,d,e,f,g);mv_Doc.ZoomBMIndex=0}}function mv_selRecordsStart(b,a,d,c,e){var f=mv_Map.Layers.item(a),g=b;f.XMLAccess&&(g=mv_selRecords(b,a));mv_selRecords2(f.XMLAccess,g,a,a,d,c,e,20)}
function mv_makeSQLString2(b,a,d){d?(" "==a&&(a=""),b="="+mv_quoteSQLString(b.XMLAccess,a)):b="="+a;return b}function mv_selRecords(b,a){var d=null,c=mv_loadAttrTableFile(a,!0);return null==c?d:d=c.query(b)}function mv_selRecords2(b,a,d,c,e,f,g,h,k,m){mv_Doc.IsMobile&&(f=!1);g&&mv_clearFeatures();b?f?_mv_writeTableDoc(a,d,c,e,f,g,h,k,m):mv_selRecInsert(a,d,c,e,f,g,h,k,m):mv_selRecInsertDB(a,c,e,f,g,h)}
function _mv_writeTableDoc(b,a,d,c,e,f,g,h,k){var m="Attribute von "+mv_XMLFileArray[a].Name,l=dijit.byId("MVrectableFP");if("undefined"!=typeof l)mv_selRecInsert(b,a,d,c,e,f,g,h,k),l.bringToTop(),l.show(),l.set("title",m),l.set("style","width:auto;height:auto");else{l=mv_makeNode(document,"div",{id:"MVrectableFP","class":"tableFP"});l.style.display="none";dojo.byId("MVhtmlBody").appendChild(l);var p=dojo.byId("MVrectableContent");mv_removeEle(p);p=mv_makeNode(document,"div",{id:"MVrectableContent",
style:"margin-right:5px"});l.appendChild(p);mv_selRecInsert(b,a,d,c,e,f,g,h,k);require(["dojox/layout/FloatingPane"],function(a){a=new a({resizable:!1,dockable:!1,"class":"tableFP",title:m,style:"position:absolute;top:60px;left:30px;width:auto;height:auto;padding-bottom:10px;z-index:4;",close:function(){mv_clearSelection(this);this.hide()}},"MVrectableFP");a.startup();a.bringToTop();a.show();a.set("style","width:auto;height:auto")})}}
function _mv_getTableTop(b,a,d,c){var e="";0<d?(e+="<p>"+d+mv_Doc.getText("QueryRec1"," of ")+a+mv_Doc.getText("QueryRec2"," records selected:")+"</p>",1==c&&(b='mv_tableToExcel("MVrecTable", "'+b+'")',b="<form><input type='button' style='margin-left:10px;' value='"+mv_Doc.getText("ExportExcel","Export to Excel")+"' onclick='"+b+"'></form>",e=e+"<p>"+b+"</p>")):e+="<p>"+mv_Doc.getText("QueryNoRec","No records selected.")+"</p>";return e}
function mv_clearSelection(b){mv_clearFeatures();document.getElementById("selRecContent")&&(document.getElementById("selRecContent").innerHTML="")}function mv_recOver(b,a,d,c,e,f){d=d.split(",");mv_hiliteRec2(b,a,d,c,e,f,mv_Doc.HiQueryColor)}
function mv_selRecInsert(b,a,d,c,e,f,g,h,k){var m=window.onerror;window.onerror=mv_selRecError;if(null==b)return!1;"undefined"==typeof h&&(h=!1);var l;if(e)var p="",t=document,z=document.getElementById("MVrectableContent"),p=_mv_getTableTop(d,mv_XMLFileArray[a].count(),b.length,k);window.onerror=m;if(0==b.length)return!0;if(e){var u=mv_makeNode(t,"table",{"class":"recTable",id:"MVrecTable"});l=mv_writeTH(t,mv_XMLFileArray[a].getHeadings());u.appendChild(l);winTxt=""}k=[];for(var q,m=mv_Map.Layers.item(d),
A=m.SVGLayerProp.StyleProp,r=0;r<b.length;r++){l=b[r];a==d&&(l=l.parentNode);if(c){var n=l.selectSingleNode("ext").firstChild.nodeValue.split(",");if(0==r)var v=parseFloat(n[0]),w=parseFloat(n[1]),x=parseFloat(n[2]),y=parseFloat(n[3]);v=Math.min(v,parseFloat(n[0]));w=Math.max(w,parseFloat(n[1]));x=Math.min(x,parseFloat(n[2]));y=Math.max(y,parseFloat(n[3]))}if(f||h)q=l.getAttributeNode("id").value,q=mv_getRecIdsFromXMLFile(l.selectSingleNode("ts"),q),f&&(k=k.concat(q));e&&(l=mv_writeRec(t,l,h,winTxt,
0==r%2?!0:!1,{},q,A),u.appendChild(l))}mv_Map.UseScaleInfo=!1;c?mv_zoomToExtent(v,w,x,y,g):f&&m.isTiled()&&m.TileRules.getSpecificTiles(d,k);mv_Map.UseScaleInfo=!0;f&&(mv_SelRecColors=new MV.ColorList({recIds:k,prop:A,doColor:!0}));e&&(z.innerHTML=p,z.appendChild(u))}function mv_selRecError(){mv_alert("Syntax Error")}
function mv_makeSQLString(b){for(b=b.replace(/<>/g,"!=");-1!=b.indexOf("\t");)b=b.replace(/\t/g," ");for(;-1!=b.indexOf("like");){var a=b.substr(b.indexOf("like")+6,b.length),a=a.substring(0,a.indexOf('"')),d=b.substring(0,b.indexOf("like")-1);-1!=d.lastIndexOf(" ")&&(d=d.substr(d.lastIndexOf(" ")+1,d.length));var c=d+' like "'+a+'"',e="";0==a.indexOf("%")?(a=a.substr(1,a.length),"%"==a.substr(a.length-1,1)?(a=a.substring(0,a.indexOf("%")),e="contains("+d+",'"+a+"')"):e="'"+a+"' = substring("+d+",string-length("+
d+") - "+(a.length-1)+")"):(-1!=a.indexOf("%")&&(a=a.substring(0,a.indexOf("%"))),e="starts-with("+d+",'"+a+"')");b=b.replace(c,e)}return b}function mv_writeTH(b,a,d){for(var c=mv_makeNode(b,"tr",{}),e,f=0;f<a.length;f++)e=a[f],0!=e.Visible&&(e=mv_makeFullNode(b,"th",{},e.Alias),null!=d&&e.setAttribute("class",d),c.appendChild(e));return c}
function mv_writeRec(b,a,d,c,e,f,g,h){var k=mv_makeNode(b,"tr",{});0==e&&mv_setAttr(k,{"class":"recTableBGAlter"});d&&(d=a.selectSingleNode("ext").firstChild.nodeValue,mv_setAttr(k,{onmouseover:c+"mv_recOver('"+h+"','"+d+"','"+g+"',this,window,event);",onmouseout:c+"mv_recOut(this);"}));a=a.selectSingleNode("c");for(g=0;g<a.childNodes.length;g++)d=a.childNodes.item(g),1==d.nodeType&&(h="",d.hasChildNodes()&&(h=d.firstChild.nodeValue),""!=h&&(h=[h,!0,!0,c]),h=mv_makeFullNode(b,"td",f,h),k.appendChild(h));
return k};